[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#3BA8A8"  # Color turquesa del logo
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#212529"
font = "sans serif"

[theme.colors]
accent = "#FF6B35"  # Color naranja del logo
highlight = "#3BA8A8"  # Color turquesa del logo