
[server]
address = "0.0.0.0"
port = 8501
enableCORS = true
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00CED1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E0FFFF"
textColor = "#2F4F4F"
font = "sans serif"
